site_name: 'soluble-japha'
site_description: 'PHP Java interop'
site_author: 'Sébastien Vanvelthem'
site_url: http://docs.soluble.io/soluble-japha/

# Repository
repo_name: 'soluble-japha'
repo_url: 'https://github.com/belgattitude/soluble-japha'

# Copyright
copyright: 'Copyright &copy; 2017 Sébastien Vanvelthem'

docs_dir: doc
site_dir: build/doc
edit_uri: https://github.com/belgattitude/soluble-japha/edit/master/doc/

pages:
    - { 'Introduction': index.md }
    - { 'Getting started': [
            { 'PHP install': install_client.md },
            { 'JavaBridge server': install_server.md }
        ]
      }
    - { 'Usage' : [
          { 'Connection': bridge_connection.md },
          { 'Language basics': language_basics.md },
          { 'Useful functions': language_useful_functions.md },
          { 'Handling exceptions': language_exceptions.md },
          { 'Recipes': language_recipes.md }

      ]}
    - { 'Performance' : [
          { 'How it works': bridge_how_it_works.md },
          { 'Optimizations': language_optimizations.md },
          { 'Benchmarks': bridge_benchmarks.md },
        ]
      }
    - { 'Advanced' : [
          { 'Servlet functions': bridge_servlet_functions.md },
          { 'Servlet session': bridge_servlet_session.md },
          { 'Servlet context': bridge_servlet_context.md }
      ]}
    - { 'Notes' : [
          { 'Limitations': notes_limitations.md },
          { 'Legacy version': notes_legacy.md },
          { 'Java install': server/install_java.md },
          { 'Tomcat install': server/install_tomcat.md },

      ]}
    - { 'Standards & quality': notes_implementation.md }


# Documentation and theme
theme:
  name: material

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  language: en
  logo:
    icon: 'thumbs_up_down'
  #logo: 'images/logo.svg'
  palette:
    primary: 'deep-orange'
    accent: 'light blue'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

  feature:
    tabs: true

# Options
extra:
  # If extra_css defined here ->
  # -> WARNING -  Config value: 'extra_css'.
  #    This behavior is deprecated. In version 1.0 and later they will need to be explicitly listed in the 'extra_css' config setting.
  #extra_css:
  #  - 'stylesheets/extra.css'
  #  - 'stylesheets/monokai.css'
  # Has been modev out of 'extra' section, see extra_css below
  social:
    - type: 'github'
      link: 'https://github.com/belgattitude/soluble-japha'

extra_css:
  - 'stylesheets/extra.css'
  - 'stylesheets/monokai.css'

google_analytics:
  - 'UA-92890300-1'
  - 'auto'

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite(guess_lang=false)
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc(permalink=true)
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde